Ensure all compatibility tests are used in CI

diff --git a/.cirrus.yml b/.cirrus.yml
--- a/.cirrus.yml
+++ b/.cirrus.yml
@@ -33,6 +33,17 @@ stable_test_task:
         cargo +stable fmt --all -- --check;
         popd;
       done
+  all_compatibility_tests_used_script:
+    - >
+      for n in compatibility-tests/*; do
+        n=$(basename $n);
+        if grep -q $n .cirrus.yml; then
+          echo "$n found";
+        else
+          echo "$n missing";
+          exit 1;
+        fi;
+      done
   before_cache_script: rm -rf $CARGO_HOME/registry/index
 
 doc_test_task:
